version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
  web:
    build: .
    command: bash -c "python /usr/src/django_project/manage.py migrate  &&
                      python /usr/src/django_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/django_project
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: