# Generated by Django 3.2.8 on 2021-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='static/img/', verbose_name='Обложка'),
        ),
    ]
