# Generated by Django 3.2.8 on 2021-11-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='blog/static/img/', verbose_name='Обложка'),
        ),
    ]
