# Generated by Django 3.2.8 on 2021-11-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
